version: '3'

services:
  api:
    build: .
    image: ubuntu:18.04
    expose:
      - 80
    ports:
      - 8000:80
    volumes:
      - ./:/app

  consumer:
    image: ubuntu:18.04
    command: php bin/console rabbitmq:consumer task
    depends_on:
      - rabbitmq
    volumes:
      - ./:/app

  rabbitmq:
    image: rabbitmq:3.7.5-management
    hostname: rabbitmq
    user: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /